---
- name: Dispatch scripts to workers
  hosts: workers
  become: true
  become user: root
  tasks:
    - name: Create scripts directory
      file:
        path: /home/almalinux/scripts
        state: directory
    - name: Copy scripts to scripts directory
      copy:
        src: "{{ item }}"
        dest: "/home/almalinux/scripts/{{ item }}"
      loop:
        - pipeline_script_v1.py
        - progress.py
        - results_parser_v1.py
