- name: Install Python Dependencies
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Install Python Dependencies
    ansible.builtin.pip:
      name:
        - biopython
        - torch==2.0.1
        - numpy<2.0
        - scipy
        - faiss-cpu
        - einops
        - matplotlib
        - natsort
        - networkx
        - rotary_embedding_torch
      state: latest