- name: Install and configure hadoop
  hosts: all
  tasks: 
  - name: Download hadoop
    ansible.builtin.get_url:
      dest: /home/almalinux/hadoop.tar.gz
      url: "https://dlcdn.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0.tar.gz"
  - name: Unpack tgz file
    ansible.builtin.unarchive:
      dest: /home/almalinux/
      remote_src: true
      src: /home/almalinux/hadoop.tar.gz
  - name: Set hadoop environment
    ansible.builtin.blockinfile:
      path: /home/almalinux/.bashrc
      block: |
        export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
        export HADOOP_HOME=/home/almalinux/hadoop-3.4.0
        export HADOOP_INSTALL=$HADOOP_HOME
        export YARN_HOME=$HADOOP_HOME
        export PATH=$PATH:$HADOOP_INSTALL/bin:$HOME/spark-3.5.3-bin-hadoop3-scala2.13/bin
        export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
        export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
        export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HADOOP_HOME/lib/native
      state: present
  - name: config core-site.xml for s3a
    ansible.builtin.blockinfile:
      path: /home/almalinux/hadoop-3.4.0/etc/hadoop/core-site.xml
      insertafter: <configuration>
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        <property>
            <name>fs.default.name</name>
            <value>hdfs://mgmtnode:9000/</value>
        </property>
        <property>
            <name>fs.default.FS</name>
            <value>hdfs://mgmtnode:9000/</value>
        </property>
        <property>
            <name>fs.s3a.impl</name>
            <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
        </property>
        <property>
            <name>fs.s3a.access.key</name>
            <value>{{ minio_access_key }}</value>
        </property>
        <property>
            <name>fs.s3a.secret.key</name>
            <value>{{ minio_secret_key }}</value>
        </property>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>{{ minio_endpoint }}</value>
        </property>
        <property>
            <name>fs.s3a.connection.ssl.enabled</name>
            <value>false</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
      state: present
  - name: config hdfs-site.xml
    ansible.builtin.blockinfile:
      path: /home/almalinux/hadoop-3.4.0/etc/hadoop/hdfs-site.xml
      insertafter: <configuration>
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        <property>
            <name>dfs.datanode.data.dir</name>
            <value>/opt/hadoop_tmp/hdfs/datanode</value>
            <final>true</final>
        </property>
        <property>
            <name>dfs.namenode.name.dir</name>
            <value>/opt/hadoop_tmp/hdfs/namenode</value>
            <final>true</final>
        </property>
        <property>
            <name>dfs.namenode.http-address</name>
            <value>mgmtnode:50070</value>
        </property>
        <property>
            <name>dfs.replication</name>
            <value>3</value>
        </property>
      state: present
  - name: config yarn-site.xml
    ansible.builtin.blockinfile:
      path: /home/almalinux/hadoop-3.4.0/etc/hadoop/yarn-site.xml
      insertafter: <configuration>
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        <property>
            <name>yarn.resourcemanager.resource-tracker.address</name>
            <value>mgmtnode:8025</value>
        </property>
        <property>
            <name>yarn.resourcemanager.scheduler.address</name>
            <value>mgmtnode:8035</value>
        </property>
        <property>
            <name>yarn.resourcemanager.address</name>
            <value>mgmtnode:8050</value>
        </property>
        <property>
            <name>yarn.log-aggregation-enable</name>
            <value>true</value>
        </property>
      state: present
  - name: config mapred-site.xml
    ansible.builtin.blockinfile:
      path: /home/almalinux/hadoop-3.4.0/etc/hadoop/mapred-site.xml
      insertafter: <configuration>
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        <property>
            <name>mapreduce.job.tracker</name>
            <value>mgmtnode:5431</value>
        </property>
        <property>
            <name>mapred.framework.name</name>
            <value>yarn</value>
        </property>
      state: present
  - name: fix JAVA_HOME in haddop-env.sh
    ansible.builtin.blockinfile:
      path: /home/almalinux/hadoop-3.4.0/etc/hadoop/hadoop-env.sh 
      insertafter: "# export JAVA_HOME="
      block: |
        export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
      state: present